name: admin
description: Calendar App.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: "^3.7.0" # ✅ Updated to resolve warning

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.1


  # ✅ Firebase packages removed
  # firebase_core: ^2.25.4
  # firebase_auth: ^4.16.0

  # State Management & Routing
  flutter_riverpod: ^2.3.6
  flexify: ^2.1.1

  # Networking
  http: ^1.2.2

  # Storage
  shared_preferences: ^2.0.15
  sqflite_common_ffi: ^2.3.4+4

  # Files
  pdf: ^3.11.2
  file_picker: ^9.2.1
  open_file: ^3.5.10
  path_provider: ^2.1.5
  excel: ^4.0.6

  # Design & UI
  sizer: ^3.0.4
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  skeletonizer: ^1.4.3
  shimmer: ^3.0.0
  country_flags: ^2.2.0

  # Toasts & Notifications
  toastification: ^2.3.0

  # Charts & Graphs
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^28.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  macos: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/fonts/
    - assets/files/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Tajawal-Medium
      fonts:
        - asset: assets/fonts/Tajawal-Medium.ttf
