// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAHenap4vu8rYMXPbQhrJ1KkQSJRqFv1zY',
//     appId: '1:640478539531:web:37c03fa260e01641eabc0e',
//     messagingSenderId: '640478539531',
//     projectId: 'calendo-2e345',
//     authDomain: 'calendo-2e345.firebaseapp.com',
//     storageBucket: 'calendo-2e345.firebasestorage.app',
//     measurementId: 'G-X6EWW5G9EZ',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCYtlRohic2_GpwydVUnowYpwWwSil5YL8',
//     appId: '1:640478539531:android:94472b9859a935f0eabc0e',
//     messagingSenderId: '640478539531',
//     projectId: 'calendo-2e345',
//     storageBucket: 'calendo-2e345.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCwsGup9TrWSRCkImzy6VOZLYvXsbzr8C4',
//     appId: '1:640478539531:ios:57292067c871412eeabc0e',
//     messagingSenderId: '640478539531',
//     projectId: 'calendo-2e345',
//     storageBucket: 'calendo-2e345.firebasestorage.app',
//     iosBundleId: 'com.example.calendarApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCwsGup9TrWSRCkImzy6VOZLYvXsbzr8C4',
//     appId: '1:640478539531:ios:57292067c871412eeabc0e',
//     messagingSenderId: '640478539531',
//     projectId: 'calendo-2e345',
//     storageBucket: 'calendo-2e345.firebasestorage.app',
//     iosBundleId: 'com.example.calendarApp',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAHenap4vu8rYMXPbQhrJ1KkQSJRqFv1zY',
//     appId: '1:640478539531:web:758ab09b750362d9eabc0e',
//     messagingSenderId: '640478539531',
//     projectId: 'calendo-2e345',
//     authDomain: 'calendo-2e345.firebaseapp.com',
//     storageBucket: 'calendo-2e345.firebasestorage.app',
//     measurementId: 'G-HFXV39RMED',
//   );
// }
